name: Release detect-angular-dashboards

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-arm64-small

    permissions:
      contents: write # Needed to create releases and tags
      pull-requests: write # Needed to create release PRs
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Get secrets from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@a37de51f3d713a30a9e4b21bcdfbd38170020593 # get-vault-secrets/v1.3.0
        with:
          common_secrets: |
            GITHUB_APP_ID=plugins-platform-bot-app:app-id
            GITHUB_APP_PRIVATE_KEY=plugins-platform-bot-app:private-key
          export_env: false

      - name: Generate GitHub token
        id: generate-github-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ fromJSON(steps.get-secrets.outputs.secrets).GITHUB_APP_ID }}
          private-key: ${{ fromJSON(steps.get-secrets.outputs.secrets).GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.ref_name }}
          token: ${{ steps.generate-github-token.outputs.token }}

      # Whenever there is a new release, build detect-angular-dashboards
      # with the new version in the linker fields and attach the build artifacts to the GitHub release.

      - name: Setup
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/setup

      - name: Build and package all
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mage package "${PACKAGE_NAME}"
        env:
          PACKAGE_NAME: ${{ steps.release.outputs.tag_name }}

      - name: Attach build artifacts to release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          gh release upload "${TAG_NAME}" ./dist/artifacts/${TAG_NAME}/*.zip
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generate-github-token.outputs.token }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
