name: CI

on:
  workflow_call:
    inputs:
      commit-hash:
        type: string
        description: "The commit hash to use for build and package step. Defaults to `github.sha` if not provided."
        required: false
        default: ""
      upload-artifacts:
        type: boolean
        description: "Whether to upload build artifacts produced by `mage package`. Defaults to `false`."
        required: false
        default: false

permissions:
  contents: read

env:
  GO_VERSION: "1.24"
  GOLANGCI_LINT_VERSION: v2.5.0
  MAGE_VERSION: v1.15.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-arm64-small
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: |
            "./..." --timeout=7m

  build-test:
    name: Build and test
    runs-on: ubuntu-arm64-small
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Mage
        uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3.1.0
        with:
          version: ${{ env.MAGE_VERSION }}
          install-only: true
      - name: Test
        run: mage test
      - name: Build and package all
        if: ${{ inputs.upload-artifacts }}
        run: mage package ${COMMIT_HASH}
        env:
          COMMIT_HASH: ${{ inputs.commit-hash || github.sha }}
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-artifacts
          path: dist/artifacts/${{ inputs.commit-hash || github.sha }}/*.zip
          retention-days: 3
