name: CI

on:
  workflow_call:

permissions:
  contents: read

env:
  GO_VERSION: "1.25"
  GOLANGCI_LINT_VERSION: v2.4.0
  MAGE_VERSION: v2.5.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-arm64-small
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: |
            "./..." --timeout=7m

  test:
    name: Test
    runs-on: ubuntu-arm64-small
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Mage
        uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3.1.0
        with:
          version: ${{ env.MAGE_VERSION }}
          install-only: true
      - name: Test
        run: mage test

  # TODO: upload build artifact
